const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94703170368"
const SESSION_ID = "PRABATH-MD~fSRVjThY#PMlpzJsKTeODhTdmKSe2kAgRp8G_iQZoyXdlHgpYGZg"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
